version: '3.8'

services:
  server:
    restart: on-failure
    build:
      context: ..
      dockerfile: ./cacophony/server/Dockerfile
    ports:
      - "${CACOPHONY_SERVER_PORT}:8080"
    environment:
      - DB_HOST=${CACOPHONY_DB_HOST}
      - DB_PORT=${CACOPHONY_DB_PORT}
      - DB_USER=${CACOPHONY_DB_USER}
      - DB_PASSWORD=${CACOPHONY_DB_PASSWORD}
      - DB_NAME=${CACOPHONY_DB_NAME}
      - JWT_KEY=${JWT_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${CACOPHONY_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CACOPHONY_DB_NAME}
      MYSQL_USER: ${CACOPHONY_DB_USER}
      MYSQL_PASSWORD: ${CACOPHONY_DB_PASSWORD}
    ports:
      - "${CACOPHONY_DB_PORT}:3306"
    volumes:
      - CACOPHONY_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  CACOPHONY_data:
