version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: ./cacophony/server/Dockerfile
    ports:
      - "${CACOPHONY_SERVER_PORT}:8080"
    environment:
      - DB_HOST=${CACOPHONY_DB_HOST}
      - DB_PORT=${CACOPHONY_DB_PORT}
      - DB_USER=${CACOPHONY_DB_USER}
      - DB_PASSWORD=${CACOPHONY_DB_PASSWORD}
      - DB_NAME=${CACOPHONY_DB_NAME}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${CACOPHONY_DB_PASSWORD}
      MYSQL_DATABASE: ${CACOPHONY_DB_NAME}
    ports:
      - "${CACOPHONY_DB_PORT}:3306"
    volumes:
      - CACOPHONY_data:/var/lib/mysql

volumes:
  CACOPHONY_data:
