syntax = "proto3";

package cacophony;
option go_package = "cacophony/cacophony";

service ChatService {
  rpc ChatStream(stream Message) returns (stream Message);
  // User account management
  rpc CreateAccount (CreateAccountRequest) returns (CreateAccountResponse);
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc Friend (FriendRequest) returns (FriendResponse);
}

// User Account Messages
message CreateAccountRequest {
  string username = 1;
  string password = 2;
  string email = 3;
}

message FriendRequest {
  string username = 1;
}

message FriendResponse {
  string response = 1;
}

message CreateAccountResponse {
  string token = 1;
  string message = 2;
  bool success = 3;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginResponse {
  string token = 1;
  bool success = 2;
}

enum ReceiverType {
  USER = 0;
  GROUP = 1;
}

message MessageErr {
  bool success = 1;
  string error = 2;
}


message Message {
  string sender = 1;
  string receiver = 2;   // Could represent either a user or group ID
  ReceiverType receiverType = 3;  // New field to distinguish between user and group
  string content = 4;
  int64 timestamp = 5;
}

// Group Management
message CreateGroupRequest {
  string groupName = 1;
  string token = 2;
}

message CreateGroupResponse {
  string groupId = 1;
  string message = 2;
  bool success = 3;
}

message AddUserToGroupRequest {
  string token = 1;
  string groupId = 2;
  string userId = 3;
}

message AddUserToGroupResponse {
  bool success = 1;
  string message = 2;
}
